### ISSUE TITLE
Configure Portal Homepage

### ISSUE THREAD

**Issue by jonathanbernal25** [davegarvey/tyk-pro-docker-demo-extended#5]
http://localhost:3000/portal/:
"Home page not found"

**Comment by davegarvey** [comment]
Can't replicate this

**Comment by davegarvey** [comment]
@jonathanbernal25 please can you check this against the latest master?

**Comment by joshblakeley** [comment]
This works fine for me - only problem i occasially get is portal link takes me to `localhost:8080/portal` instead of 3000

**Comment by davegarvey** [comment]
Thanks Josh, will close and reopen a new issue for that link
